/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Drug } from "./Drug";
import { DrugCountArgs } from "./DrugCountArgs";
import { DrugFindManyArgs } from "./DrugFindManyArgs";
import { DrugFindUniqueArgs } from "./DrugFindUniqueArgs";
import { DeleteDrugArgs } from "./DeleteDrugArgs";
import { DrugService } from "../drug.service";
@graphql.Resolver(() => Drug)
export class DrugResolverBase {
  constructor(protected readonly service: DrugService) {}

  async _drugsMeta(
    @graphql.Args() args: DrugCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Drug])
  async drugs(@graphql.Args() args: DrugFindManyArgs): Promise<Drug[]> {
    return this.service.drugs(args);
  }

  @graphql.Query(() => Drug, { nullable: true })
  async drug(@graphql.Args() args: DrugFindUniqueArgs): Promise<Drug | null> {
    const result = await this.service.drug(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Drug)
  async deleteDrug(@graphql.Args() args: DeleteDrugArgs): Promise<Drug | null> {
    try {
      return await this.service.deleteDrug(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
